"""
Signal generator for mock ESP32 simulator.

This module provides synthetic IMU signal generation for testing
purposes. It generates realistic-looking data patterns that can
be used to test the system without physical hardware.

Important Disclaimer:
The synthetic signals generated by this module are for SOFTWARE
TESTING ONLY. They do NOT represent medically valid Parkinsonian
tremor or clinically valid Freezing of Gait (FOG) patterns.

Any similarity to actual tremor or FOG patterns is coincidental
and should NOT be used for clinical validation or research claims.
"""

import math
import random
import time
from typing import Tuple

import numpy as np


class SignalGenerator:
    """
    Synthetic IMU signal generator for testing.

    Generates realistic-looking but medically invalid sensor data
    for software testing purposes.
    """

    def __init__(self, sampling_rate_hz: int = 50):
        """
        Initialize signal generator.

        Args:
            sampling_rate_hz: Sampling rate in Hz
        """
        self.sampling_rate = sampling_rate_hz
        self.time_step = 1.0 / sampling_rate_hz
        self.time_offset = 0.0

    def generate_baseline(
        self,
        duration_seconds: float = 1.0,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Generate baseline (normal) IMU data.

        Args:
            duration_seconds: Duration of signal in seconds

        Returns:
            Tuple[np.ndarray, np.ndarray]: (hand_data, shoe_data)
                Each array has shape (N, 6) with columns:
                [ax, ay, az, gx, gy, gz]
        """
        n_samples = int(duration_seconds * self.sampling_rate)

        # Hand baseline: slight noise around gravity
        hand_data = np.zeros((n_samples, 6))
        hand_data[:, 0] = np.random.normal(0, 0.1, n_samples)  # ax
        hand_data[:, 1] = np.random.normal(0, 0.1, n_samples)  # ay
        hand_data[:, 2] = 9.8 + np.random.normal(0, 0.05, n_samples)  # az (gravity)
        hand_data[:, 3] = np.random.normal(0, 0.5, n_samples)  # gx
        hand_data[:, 4] = np.random.normal(0, 0.5, n_samples)  # gy
        hand_data[:, 5] = np.random.normal(0, 0.5, n_samples)  # gz

        # Shoe baseline: slight gait-like movement
        shoe_data = np.zeros((n_samples, 6))
        t = np.linspace(0, duration_seconds, n_samples)
        shoe_data[:, 0] = 0.5 * np.sin(2 * np.pi * 1.5 * t) + np.random.normal(0, 0.1, n_samples)
        shoe_data[:, 1] = np.random.normal(0, 0.1, n_samples)
        shoe_data[:, 2] = 9.8 + np.random.normal(0, 0.1, n_samples)
        shoe_data[:, 3] = np.random.normal(0, 1.0, n_samples)
        shoe_data[:, 4] = np.random.normal(0, 1.0, n_samples)
        shoe_data[:, 5] = np.random.normal(0, 1.0, n_samples)

        return hand_data, shoe_data

    def generate_tremor_like(
        self,
        duration_seconds: float = 1.0,
        frequency_hz: float = 5.0,
        amplitude: float = 0.5,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Generate synthetic tremor-like signals for testing.

        This generates a sinusoidal pattern that resembles tremor
        but is NOT medically valid. For software testing only.

        Args:
            duration_seconds: Duration of signal in seconds
            frequency_hz: Tremor-like frequency in Hz
            amplitude: Tremor-like amplitude

        Returns:
            Tuple[np.ndarray, np.ndarray]: (hand_data, shoe_data)
        """
        n_samples = int(duration_seconds * self.sampling_rate)
        t = np.linspace(0, duration_seconds, n_samples)

        # Hand: add tremor-like oscillation
        hand_data = np.zeros((n_samples, 6))
        tremor_signal = amplitude * np.sin(2 * np.pi * frequency_hz * t)
        hand_data[:, 0] = tremor_signal + np.random.normal(0, 0.1, n_samples)  # ax
        hand_data[:, 1] = 0.3 * tremor_signal + np.random.normal(0, 0.1, n_samples)  # ay
        hand_data[:, 2] = 9.8 + np.random.normal(0, 0.05, n_samples)
        hand_data[:, 3] = amplitude * 10 * np.cos(2 * np.pi * frequency_hz * t) + np.random.normal(0, 0.5, n_samples)
        hand_data[:, 4] = np.random.normal(0, 0.5, n_samples)
        hand_data[:, 5] = np.random.normal(0, 0.5, n_samples)

        # Shoe: baseline gait (unaffected by hand tremor)
        shoe_data, _ = self.generate_baseline(duration_seconds)

        return hand_data, shoe_data

    def generate_gait_like(
        self,
        duration_seconds: float = 1.0,
        cadence_hz: float = 1.5,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Generate synthetic gait-like signals for testing.

        This generates periodic patterns that resemble walking
        but are NOT clinically valid FOG patterns. For testing only.

        Args:
            duration_seconds: Duration of signal in seconds
            cadence_hz: Gait cadence in Hz

        Returns:
            Tuple[np.ndarray, np.ndarray]: (hand_data, shoe_data)
        """
        n_samples = int(duration_seconds * self.sampling_rate)
        t = np.linspace(0, duration_seconds, n_samples)

        # Hand: minimal movement during gait
        hand_data = np.zeros((n_samples, 6))
        hand_data[:, 0] = np.random.normal(0, 0.1, n_samples)
        hand_data[:, 1] = np.random.normal(0, 0.1, n_samples)
        hand_data[:, 2] = 9.8 + np.random.normal(0, 0.05, n_samples)
        hand_data[:, 3] = np.random.normal(0, 0.5, n_samples)
        hand_data[:, 4] = np.random.normal(0, 0.5, n_samples)
        hand_data[:, 5] = np.random.normal(0, 0.5, n_samples)

        # Shoe: gait-like periodic movement
        shoe_data = np.zeros((n_samples, 6))
        gait_signal = 1.0 * np.sin(2 * np.pi * cadence_hz * t)
        shoe_data[:, 0] = gait_signal + np.random.normal(0, 0.1, n_samples)  # ax
        shoe_data[:, 1] = 0.5 * np.abs(gait_signal) + np.random.normal(0, 0.1, n_samples)  # ay
        shoe_data[:, 2] = 9.8 + 0.3 * gait_signal + np.random.normal(0, 0.1, n_samples)
        shoe_data[:, 3] = 5.0 * np.cos(2 * np.pi * cadence_hz * t) + np.random.normal(0, 1.0, n_samples)
        shoe_data[:, 4] = np.random.normal(0, 1.0, n_samples)
        shoe_data[:, 5] = np.random.normal(0, 1.0, n_samples)

        return hand_data, shoe_data

    def generate_fog_like(
        self,
        duration_seconds: float = 1.0,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Generate synthetic FOG-like signals for testing.

        This generates signals that resemble Freezing of Gait
        but are NOT clinically valid. For software testing only.

        FOG characteristics (simplified):
        - Reduced gait amplitude
        - Increased frequency components
        - Asymmetric movement

        Args:
            duration_seconds: Duration of signal in seconds

        Returns:
            Tuple[np.ndarray, np.ndarray]: (hand_data, shoe_data)
        """
        n_samples = int(duration_seconds * self.sampling_rate)
        t = np.linspace(0, duration_seconds, n_samples)

        # Hand: minimal movement
        hand_data = np.zeros((n_samples, 6))
        hand_data[:, 0] = np.random.normal(0, 0.1, n_samples)
        hand_data[:, 1] = np.random.normal(0, 0.1, n_samples)
        hand_data[:, 2] = 9.8 + np.random.normal(0, 0.05, n_samples)
        hand_data[:, 3] = np.random.normal(0, 0.5, n_samples)
        hand_data[:, 4] = np.random.normal(0, 0.5, n_samples)
        hand_data[:, 5] = np.random.normal(0, 0.5, n_samples)

        # Shoe: FOG-like (reduced amplitude, higher frequency)
        shoe_data = np.zeros((n_samples, 6))
        fog_signal = 0.2 * np.sin(2 * np.pi * 4.0 * t)  # Higher freq, lower amp
        shoe_data[:, 0] = fog_signal + np.random.normal(0, 0.05, n_samples)
        shoe_data[:, 1] = np.random.normal(0, 0.05, n_samples)
        shoe_data[:, 2] = 9.8 + np.random.normal(0, 0.05, n_samples)
        shoe_data[:, 3] = 2.0 * np.cos(2 * np.pi * 4.0 * t) + np.random.normal(0, 0.5, n_samples)
        shoe_data[:, 4] = np.random.normal(0, 0.5, n_samples)
        shoe_data[:, 5] = np.random.normal(0, 0.5, n_samples)

        return hand_data, shoe_data
