"""
Event schemas for processed results and system events.

This module defines the Pydantic models for events generated by the
ML inference pipeline, including FOG detection events and tremor
analysis results.

Important Notes:
- FOG events are generated when FOG is detected by the ML model
- Tremor results represent model predictions, NOT clinical diagnoses
- These schemas are placeholders for future ML implementation
- Clinical validation is required before any medical use

Medical Disclaimer:
This system is a research prototype. Event labels and confidence
scores do NOT constitute medical diagnoses or clinical assessments.
"""

import uuid
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


class EventType(str, Enum):
    """
    Event types generated by the ML inference pipeline.

    Attributes:
        FOG: Freezing of Gait detection event
        TREMOR_RESULT: Tremor analysis result
    """
    FOG = "FOG"
    TREMOR_RESULT = "TREMOR_RESULT"


class TremorClass(str, Enum):
    """
    Tremor severity classification labels.

    Important: These labels are placeholders for future ML implementation.
    Actual tremor severity classification requires:
    1. Validated clinical datasets
    2. Expert annotation
    3. Clinical validation study

    Do NOT use these labels for clinical decisions.
    """
    NOT_AVAILABLE = "not_available"
    NO_TREMOR = "no_tremor"
    MILD = "mild"
    MODERATE = "moderate"
    SEVERE = "severe"


class FOGEvent(BaseModel):
    """
    Freezing of Gait detection event.

    This model represents a detected FOG event from the ML inference
    pipeline. When FOG is detected, this event triggers:
    1. Buzzer cueing on ESP32
    2. Event logging in database
    3. Dashboard notification (future)

    Medical Disclaimer:
    FOG detection confidence does NOT indicate clinical severity.
    This is a research prototype, not a medical device.
    """

    model_config = ConfigDict(
        use_enum=True,
        json_schema_extra={
            "examples": [{
                "event_id": "550e8400-e29b-41d4-a716-446655440000",
                "patient_id": "P001",
                "event_type": "FOG",
                "detected_at_ms": 1720012345678,
                "confidence": 0.91,
                "cue_triggered": True,
                "model_version": "v1.0",
            }]
        }
    )

    event_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique event identifier",
        examples=["550e8400-e29b-41d4-a716-446655440000"],
    )
    patient_id: str = Field(
        ...,
        min_length=1,
        description="Patient identifier",
        examples=["P001"],
    )
    event_type: EventType = Field(
        default=EventType.FOG,
        description="Event type identifier",
        examples=["FOG"],
    )
    detected_at_ms: int = Field(
        ...,
        gt=0,
        description="Unix epoch timestamp when FOG was detected (ms)",
        examples=[1720012345678],
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Model confidence score (0.0 to 1.0)",
        examples=[0.91],
    )
    cue_triggered: bool = Field(
        default=False,
        description="Whether buzzer cueing was triggered",
        examples=[True],
    )
    model_version: str = Field(
        default="not_trained",
        description="ML model version used for detection",
        examples=["v1.0"],
    )

    @field_validator('patient_id')
    @classmethod
    def validate_patient_id(cls, v: str) -> str:
        """Validate patient ID format."""
        if not v or not v.strip():
            raise ValueError('Patient ID cannot be empty')
        return v.strip()

    @field_validator('model_version')
    @classmethod
    def validate_model_version(cls, v: str) -> str:
        """Validate model version format."""
        if not v or not v.strip():
            raise ValueError('Model version cannot be empty')
        return v.strip()


class TremorResult(BaseModel):
    """
    Tremor analysis result from ML inference.

    This model represents tremor analysis output from the ML pipeline.
    The predicted_class indicates the model's assessment of tremor
    presence and severity.

    Medical Disclaimer:
    Tremor classification is NOT a clinical diagnosis.
    Actual tremor severity assessment requires:
    1. Validated clinical datasets with expert annotation
    2. Clinical validation study
    3. Regulatory approval (if used as medical device)

    Do NOT use these results for clinical decisions.
    """

    model_config = ConfigDict(
        use_enum=True,
        json_schema_extra={
            "examples": [{
                "event_id": "550e8400-e29b-41d4-a716-446655440000",
                "patient_id": "P001",
                "event_type": "TREMOR_RESULT",
                "detected_at_ms": 1720012345678,
                "predicted_class": "not_available",
                "confidence": None,
                "model_version": "v1.0",
            }]
        }
    )

    event_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique event identifier",
        examples=["550e8400-e29b-41d4-a716-446655440000"],
    )
    patient_id: str = Field(
        ...,
        min_length=1,
        description="Patient identifier",
        examples=["P001"],
    )
    event_type: EventType = Field(
        default=EventType.TREMOR_RESULT,
        description="Event type identifier",
        examples=["TREMOR_RESULT"],
    )
    detected_at_ms: int = Field(
        ...,
        gt=0,
        description="Unix epoch timestamp when analysis was performed (ms)",
        examples=[1720012345678],
    )
    predicted_class: TremorClass = Field(
        default=TremorClass.NOT_AVAILABLE,
        description="Predicted tremor class",
        examples=["not_available"],
    )
    confidence: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Model confidence score (0.0 to 1.0) or None if not available",
        examples=[None],
    )
    model_version: str = Field(
        default="not_trained",
        description="ML model version used for analysis",
        examples=["v1.0"],
    )

    @field_validator('patient_id')
    @classmethod
    def validate_patient_id(cls, v: str) -> str:
        """Validate patient ID format."""
        if not v or not v.strip():
            raise ValueError('Patient ID cannot be empty')
        return v.strip()

    @field_validator('model_version')
    @classmethod
    def validate_model_version(cls, v: str) -> str:
        """Validate model version format."""
        if not v or not v.strip():
            raise ValueError('Model version cannot be empty')
        return v.strip()
